# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Produce verbose output by default.
VERBOSE = 1

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pzhang/chen/move-bed

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pzhang/chen/move-bed

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pzhang/chen/move-bed/CMakeFiles /home/pzhang/chen/move-bed/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pzhang/chen/move-bed/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test_periodic

# Build rule for target.
test_periodic: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_periodic
.PHONY : test_periodic

# fast build rule for target.
test_periodic/fast:
	$(MAKE) -f CMakeFiles/test_periodic.dir/build.make CMakeFiles/test_periodic.dir/build
.PHONY : test_periodic/fast

#=============================================================================
# Target rules for targets named test_circle_move

# Build rule for target.
test_circle_move: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_circle_move
.PHONY : test_circle_move

# fast build rule for target.
test_circle_move/fast:
	$(MAKE) -f CMakeFiles/test_circle_move.dir/build.make CMakeFiles/test_circle_move.dir/build
.PHONY : test_circle_move/fast

#=============================================================================
# Target rules for targets named test_circle_spin

# Build rule for target.
test_circle_spin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_circle_spin
.PHONY : test_circle_spin

# fast build rule for target.
test_circle_spin/fast:
	$(MAKE) -f CMakeFiles/test_circle_spin.dir/build.make CMakeFiles/test_circle_spin.dir/build
.PHONY : test_circle_spin/fast

#=============================================================================
# Target rules for targets named test_circle2

# Build rule for target.
test_circle2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_circle2
.PHONY : test_circle2

# fast build rule for target.
test_circle2/fast:
	$(MAKE) -f CMakeFiles/test_circle2.dir/build.make CMakeFiles/test_circle2.dir/build
.PHONY : test_circle2/fast

#=============================================================================
# Target rules for targets named test_mvbed

# Build rule for target.
test_mvbed: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_mvbed
.PHONY : test_mvbed

# fast build rule for target.
test_mvbed/fast:
	$(MAKE) -f CMakeFiles/test_mvbed.dir/build.make CMakeFiles/test_mvbed.dir/build
.PHONY : test_mvbed/fast

#=============================================================================
# Target rules for targets named test_collision

# Build rule for target.
test_collision: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_collision
.PHONY : test_collision

# fast build rule for target.
test_collision/fast:
	$(MAKE) -f CMakeFiles/test_collision.dir/build.make CMakeFiles/test_collision.dir/build
.PHONY : test_collision/fast

test_circle2.o: test_circle2.cpp.o

.PHONY : test_circle2.o

# target to build an object file
test_circle2.cpp.o:
	$(MAKE) -f CMakeFiles/test_circle2.dir/build.make CMakeFiles/test_circle2.dir/test_circle2.cpp.o
.PHONY : test_circle2.cpp.o

test_circle2.i: test_circle2.cpp.i

.PHONY : test_circle2.i

# target to preprocess a source file
test_circle2.cpp.i:
	$(MAKE) -f CMakeFiles/test_circle2.dir/build.make CMakeFiles/test_circle2.dir/test_circle2.cpp.i
.PHONY : test_circle2.cpp.i

test_circle2.s: test_circle2.cpp.s

.PHONY : test_circle2.s

# target to generate assembly for a file
test_circle2.cpp.s:
	$(MAKE) -f CMakeFiles/test_circle2.dir/build.make CMakeFiles/test_circle2.dir/test_circle2.cpp.s
.PHONY : test_circle2.cpp.s

test_circle_move.o: test_circle_move.cpp.o

.PHONY : test_circle_move.o

# target to build an object file
test_circle_move.cpp.o:
	$(MAKE) -f CMakeFiles/test_circle_move.dir/build.make CMakeFiles/test_circle_move.dir/test_circle_move.cpp.o
.PHONY : test_circle_move.cpp.o

test_circle_move.i: test_circle_move.cpp.i

.PHONY : test_circle_move.i

# target to preprocess a source file
test_circle_move.cpp.i:
	$(MAKE) -f CMakeFiles/test_circle_move.dir/build.make CMakeFiles/test_circle_move.dir/test_circle_move.cpp.i
.PHONY : test_circle_move.cpp.i

test_circle_move.s: test_circle_move.cpp.s

.PHONY : test_circle_move.s

# target to generate assembly for a file
test_circle_move.cpp.s:
	$(MAKE) -f CMakeFiles/test_circle_move.dir/build.make CMakeFiles/test_circle_move.dir/test_circle_move.cpp.s
.PHONY : test_circle_move.cpp.s

test_circle_spin.o: test_circle_spin.cpp.o

.PHONY : test_circle_spin.o

# target to build an object file
test_circle_spin.cpp.o:
	$(MAKE) -f CMakeFiles/test_circle_spin.dir/build.make CMakeFiles/test_circle_spin.dir/test_circle_spin.cpp.o
.PHONY : test_circle_spin.cpp.o

test_circle_spin.i: test_circle_spin.cpp.i

.PHONY : test_circle_spin.i

# target to preprocess a source file
test_circle_spin.cpp.i:
	$(MAKE) -f CMakeFiles/test_circle_spin.dir/build.make CMakeFiles/test_circle_spin.dir/test_circle_spin.cpp.i
.PHONY : test_circle_spin.cpp.i

test_circle_spin.s: test_circle_spin.cpp.s

.PHONY : test_circle_spin.s

# target to generate assembly for a file
test_circle_spin.cpp.s:
	$(MAKE) -f CMakeFiles/test_circle_spin.dir/build.make CMakeFiles/test_circle_spin.dir/test_circle_spin.cpp.s
.PHONY : test_circle_spin.cpp.s

test_collision.o: test_collision.cpp.o

.PHONY : test_collision.o

# target to build an object file
test_collision.cpp.o:
	$(MAKE) -f CMakeFiles/test_collision.dir/build.make CMakeFiles/test_collision.dir/test_collision.cpp.o
.PHONY : test_collision.cpp.o

test_collision.i: test_collision.cpp.i

.PHONY : test_collision.i

# target to preprocess a source file
test_collision.cpp.i:
	$(MAKE) -f CMakeFiles/test_collision.dir/build.make CMakeFiles/test_collision.dir/test_collision.cpp.i
.PHONY : test_collision.cpp.i

test_collision.s: test_collision.cpp.s

.PHONY : test_collision.s

# target to generate assembly for a file
test_collision.cpp.s:
	$(MAKE) -f CMakeFiles/test_collision.dir/build.make CMakeFiles/test_collision.dir/test_collision.cpp.s
.PHONY : test_collision.cpp.s

test_mvbed.o: test_mvbed.cpp.o

.PHONY : test_mvbed.o

# target to build an object file
test_mvbed.cpp.o:
	$(MAKE) -f CMakeFiles/test_mvbed.dir/build.make CMakeFiles/test_mvbed.dir/test_mvbed.cpp.o
.PHONY : test_mvbed.cpp.o

test_mvbed.i: test_mvbed.cpp.i

.PHONY : test_mvbed.i

# target to preprocess a source file
test_mvbed.cpp.i:
	$(MAKE) -f CMakeFiles/test_mvbed.dir/build.make CMakeFiles/test_mvbed.dir/test_mvbed.cpp.i
.PHONY : test_mvbed.cpp.i

test_mvbed.s: test_mvbed.cpp.s

.PHONY : test_mvbed.s

# target to generate assembly for a file
test_mvbed.cpp.s:
	$(MAKE) -f CMakeFiles/test_mvbed.dir/build.make CMakeFiles/test_mvbed.dir/test_mvbed.cpp.s
.PHONY : test_mvbed.cpp.s

test_periodic.o: test_periodic.cpp.o

.PHONY : test_periodic.o

# target to build an object file
test_periodic.cpp.o:
	$(MAKE) -f CMakeFiles/test_periodic.dir/build.make CMakeFiles/test_periodic.dir/test_periodic.cpp.o
.PHONY : test_periodic.cpp.o

test_periodic.i: test_periodic.cpp.i

.PHONY : test_periodic.i

# target to preprocess a source file
test_periodic.cpp.i:
	$(MAKE) -f CMakeFiles/test_periodic.dir/build.make CMakeFiles/test_periodic.dir/test_periodic.cpp.i
.PHONY : test_periodic.cpp.i

test_periodic.s: test_periodic.cpp.s

.PHONY : test_periodic.s

# target to generate assembly for a file
test_periodic.cpp.s:
	$(MAKE) -f CMakeFiles/test_periodic.dir/build.make CMakeFiles/test_periodic.dir/test_periodic.cpp.s
.PHONY : test_periodic.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... test_periodic"
	@echo "... rebuild_cache"
	@echo "... test_circle_move"
	@echo "... edit_cache"
	@echo "... test_circle_spin"
	@echo "... test_circle2"
	@echo "... test_mvbed"
	@echo "... test_collision"
	@echo "... test_circle2.o"
	@echo "... test_circle2.i"
	@echo "... test_circle2.s"
	@echo "... test_circle_move.o"
	@echo "... test_circle_move.i"
	@echo "... test_circle_move.s"
	@echo "... test_circle_spin.o"
	@echo "... test_circle_spin.i"
	@echo "... test_circle_spin.s"
	@echo "... test_collision.o"
	@echo "... test_collision.i"
	@echo "... test_collision.s"
	@echo "... test_mvbed.o"
	@echo "... test_mvbed.i"
	@echo "... test_mvbed.s"
	@echo "... test_periodic.o"
	@echo "... test_periodic.i"
	@echo "... test_periodic.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

